### ISSUE TITLE
[Question] additional slurm directives

### ISSUE THREAD

**Issue by AlessandroZavoli** [albanie/yaspi#1]
How can I add additional slurm directives such as account "#SBATCH -A account-name" ?

**Comment by albanie** [comment]
Hi @AlessandroZavoli, thanks for raising this.  I've added support for custom directives, which you can either do from the command line (now added to the README), or if you use `Yaspi` directly in python code you would do something like this:

```
    # set up yaspi object with options
    yaspi_options = ...

    # pass in your custom directives (can have multiple separated by a newline character)
    yaspi_options["custom_directives"] = "#SBATCH -A account-name"

    # create Yaspi object 
    yaspi = Yaspi(
        cmd="python yaspi_test/misc/hello_world.py",
        job_name="test_yaspi",
        job_queue="",
        job_array_size=1,
        **yaspi_options,
    )
```

Feel free to re-open if you have further issues/questions.
